language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
before_install:
    - sudo apt-get install tree -y
script:
    # build projects
    - cd Compile.and.Execute/src/
    - echo Building Projects

    # needs sudo to write to different output folders
    - |
      sudo dotnet build Sigged.Compiling.Core/Sigged.Compiling.Core.csproj -c Release
      sudo dotnet build Sigged.Compiling.Core.Tests/Sigged.Compiling.Core.Tests.csproj -c Release
      sudo dotnet build Sigged.CodeHost.Worker/Sigged.CodeHost.Worker.csproj -c Release
      sudo dotnet build Sigged.CsC.NetCore.Web/Sigged.CsC.NetCore.Web.csproj -c Release
      sudo dotnet build Sigged.CodeHost.Worker.Tests/Sigged.CodeHost.Worker.Tests.csproj -c Release

    # test projects
    - echo Testing Projects
    - |
      dotnet test --no-build Sigged.Compiling.Core.Tests/Sigged.Compiling.Core.Tests.csproj -c Release --verbosity normal
      dotnet test --no-build Sigged.CodeHost.Worker.Tests/Sigged.CodeHost.Worker.Tests.csproj -c Release --verbosity normal

    - echo Building Docker image
    - docker build -f Dockerfile -t "${DOCKERHUB_CONTAINERNAME}" .

after_success:
    # push to docker hub
    - |
      if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then
        echo Pushing to Docker Hub
        docker login -u "${DOCKERHUB_USER}" -p "${DOCKERHUB_PASS}"
        docker push "${DOCKERHUB_CONTAINERNAME}"
      else
        echo "Skipping docker push. This build was not a push to master, or is a pull request"
      fi
